de.dlr.sc.virsat.p2updatesite/category.xml
de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel
de.dlr.sc.virsat.target/tmodel-src/core_release_4_9_0.tmodel

- Create new release with deployed target.feature

Release 4.9.0 #3

---

projectSet/projectSet.psf

Added old ProjectSet definition with updated github URLs + updated root project path

Add file with project sets - (Task #22)

---

.travis.yml

Close #48
---
Task #48: Add trusty flag to travis

Added trusty flag - (Task #48)

---

de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java

Feature/task 41 exception if vtk view 

---

de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/shape/ShapeEditObserver.java

Using command execution that is not inserted into undo history
---
Task #38: Exclude received scenegraph updates from undo history

Using history free command execution - (Task #38)

---

de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/comparison/CompareModelPropertyTest.java
de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/dialogs/CompareModelPropertyDialog.java
de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/handler/CompareModelPropertyHandler.java
de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/comparison/CompareModelProperty.java

Closes #58
---
Task #58: Extend Visualization Comparison logic to also work on
UniValuePropertyInstances

Added support for selecting Qudv Property in vis comparison - (Task #58)

---

de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkTreeManager.java

Fix #60
- Removed incorrect deletion of actors in scene updated
---
Task #60: No axes appear when restarting the 3D View

Removed incorrect line - (Task #60)

---

de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/DebugClientView.java

Setting debug client before creation of listener threads - (Task #55)

---

de.dlr.sc.virsat.build.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.build.ui/build.properties
de.dlr.sc.virsat.build.ui/plugin.properties

- Removed dead plugin.properties in build.ui
- Removed references to plugin.properties
---
Task #81: Evaluate necessity of plugin.properties file in build.ui
plugin

Removed plugin.properties in build.ui - (Task #81)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetIUuid.java

Make UUID selectable from editor field.

Feature/task 88 UUID field selectedable

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java

Added waitForEditor condition for SWTBotTest cases

---

de.dlr.sc.virsat.model/META-INF/MANIFEST.MF
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelper.java

Removed dependency to google guava - (Task #35)

---

de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloatTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyIntTest.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanUnitProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java

- Implemented setting of value + unit from an input bean
- Implemented test cases
Closes #82 
---
Task #82: Add methods to setValue in a bean from another bean

Added set methods and tested them - (Task #82)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java

Use a focus manager to enable keyboard navigation in Virtual Satellite's tables

Implement table keyboard navigation in generic table snippet

---

de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel

Closes #166
---
Task #166: Add mechanical concept to Overtarget tmodels

Added mechanical concept to overtarget - (Task #166)

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/ABeanStructuralElementInstance.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/IBeanStructuralElementInstance.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/util/BeanStructuralElementInstanceHelper.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/util/BeanStructuralElementInstanceHelperTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestStructuralElementInstanceTest.java
de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelperTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelper.java

Reduced code duplication in StructuralElementInstanceHelperTest
---
Task #168: Create functionality to get all superSeis
Closes #168

Added getAllSuperSeis method for SEIs and beans - (Task #168)

---

de.dlr.sc.virsat.test.feature/feature.xml

Closes #176 
---
Task #176: Deliver mechanical.test plugin in the test.feature

Added mechanical.test plugin into the test.feature - (Task #176)

---

de.dlr.sc.virsat.model.extension.mechanical.ui/plugin.xml
de.dlr.sc.virsat.model.extension.mechanical/concept/concept.xmi
de.dlr.sc.virsat.model.extension.mechanical/concept/concept_v0_1.xmi

The generated files now contain the displayname.

Update the generated files of the mechancial concept  - (Task #181)

---

de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaProperties.java

---
Task #173: CATIA Export: Products
Closes #173

Added export of Products to Json - (Task #173)

---

de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/util/CatiaHelperTest.java
de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/util/CatiaHelper.java

Add a helper class for all kind of CATIA / JSON utility methods

Add Catia helper class - (Task #183)

---

de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java

Feature/task 180 catia export content 

---

de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatDanglingReferencesTest.java
de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatProjectResourceTest.java

Refactored VirSatDanglingReferencesTest to use AProjectTestCase

---

launchers/VirSat Core Build Development (Deploy Local).launch
launchers/VirSat Core Build Development (Deploy Unsecured).launch
pom.xml

Included doc profile in the maven configurations - (Task #291)

---

projectSet/projectSet.psf

Deleted non-existent project "...calculation.tests" and added new
project "...calculation.test" in the projectSet file.
Closes #308
---
Task #308: Update project set definition file to latest version

Update Project Set - (Task #308)

---

de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/EnumTestEnum.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryAllPropertyImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryBaseImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryCompositionArrayImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryCompositionImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryExtendsImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryIntrinsicArrayImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryReferenceArrayImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryReferenceImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestMassParametersImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestParameterImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestsFactoryImpl.java
de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestsPackageImpl.java

Cleaned project with code generator enabled
Closes #307
---
Task #307: Add latest generated DMF resources

Add generated DMF resources in extension.tests - (Task #307)

---

de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java

Feature/task 313 don't run validators from inactive concepts

---

de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadExporterTest.java
de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporterTest.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadExporter.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporter.java
de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadProperties.java

Old branch was conflicting with catia -> cad renaming, so changes had to
be copied from that branch.
---
Task #220: Clean up mechanical export products

Copied changes from previous 220 branch - (Task #220)

---

de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceSaveCommandTest.java
de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AllTests.java
de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceSaveCommand.java

Resolve proxies in DMFSaveCommand...
When first using the SEI in the command, it checks if it is a proxy... if so it resolves it.
Closes #351

Resolve potential proxies in DMFSaveCommand- (Task #351)

---

de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportPage.java
de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportWizard.java
de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportPage.java
de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportWizard.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/wizard/ConstraintTablePage.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/wizard/ConstraintTableWizard.java

Not a really elegant implementation, but the relevant views have a beta flag in their title now.
Closes #323

Tag views of beta concept as beta - (Task #323)

---

de.dlr.sc.virsat.excel.ui/plugin.xml
de.dlr.sc.virsat.model.extension.funcelectrical.ui/plugin.xml

- Updated the categories of the Excel and the Funcelectrical exporters / importers
- Improved name consistencies

Updated categories of VirSat Importers/Exporters - Task (#324)

---

de.dlr.sc.virsat.p2updatesite/category.xml
de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel

The new server feature is now being deployed to the p2 repository.
- Added server feature to category.xml
- Added server feature to overtarget libraries for development and
integration
Closes #404 
---
Task #404: Add virsat server feature to overtarget tmodel

Downstreaming server feature - (Task #404)

---

de.dlr.sc.virsat.model.calculation.tests/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilderTest.java
de.dlr.sc.virsat.model.calculation/META-INF/MANIFEST.MF
de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java

In equation builder if there are errors in ResourceSet, write them to log and show them to the user.
This has to be also merged to development.

Error reporting in equation builder on errors in resources - (Task #392)

---

de.dlr.sc.virsat.model.extension.funcelectrical/plugin.xml
de.dlr.sc.virsat.model.extension.statemachines/plugin.xml

- Changed the package names in funcelectrical and statemachine in plugin.xml
Closes #421 
---
Task #421: Rename Packages of excel plugins

Changed names in plugin.xml - (Task #421)

---

build.xml

- Changed http to https in build.xml script
---
Task #430: Use https based address to acquire jacoco jars in build
script

Updated address of jacoco jar files - (Task #430)

---

.github/ISSUE_TEMPLATE/release.md

Minor adjustment of release issue template (Task #439)

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
known_authors.txt

minor typo fix

---

de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF

Export virsat.swtbot.test package for VirSat-FDIR project to reference
Closes #447 
---
Task #447: Export swtbot.test package

Export virsat.swtbot.test package - (Task #447)

---

.mailmap
known_authors.txt

Added watollah-dlr to known authors and mailmap - (Task #505)

---

.github/ISSUE_TEMPLATE/default.md

- Add a default issue template that contains a description
#closes #492

Add default issue template - (Task #492)

---

de.dlr.sc.virsat.model.feature/feature.xml

Changed model.feature
Closes #526

Repair mat library import

---

de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AVirSatVersionControlBackendTest.java
de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/IVirSatVersionControlBackend.java
de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackend.java

- Changed the interface of the version control backend and adapted it to
the new worklow
Closes #542
---
Task #542: Adapt logic of version control backend checkin

Adapted check-in logic - (Task #542)

---

de.dlr.sc.virsat.excel.ui/plugin.xml
de.dlr.sc.virsat.model.calculation.ui/plugin.xml
de.dlr.sc.virsat.model.extension.funcelectrical.ui/plugin.xml
de.dlr.sc.virsat.model.extension.mechanical.ui/plugin.xml
de.dlr.sc.virsat.project.ui/plugin.xml
de.dlr.sc.virsat.qudv.ui/plugin.xml

in plugin.xml from "VirSat" to "Virtual Satellite"
---
closes #373: Rename VirSat Import/Export categories to "Virtual Satellite"

Renamed Import/Export/View categories- (Task #373)

---

de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF

Exporting de.dlr.sc.virsat.project.ui.wizard - (Task #553)

---

de.dlr.sc.virsat.model.edit.test/plugin.properties
de.dlr.sc.virsat.model.edit/plugin.properties
de.dlr.sc.virsat.model.external.tests.edit/plugin.properties
de.dlr.sc.virsat.model.external.tests/plugin.properties
de.dlr.sc.virsat.model.test/plugin.properties
de.dlr.sc.virsat.model/plugin.properties
de.dlr.sc.virsat.uiengine.ui/plugin.properties

Closes #474
---
Task #474: Inconsistent Vendor naming in plugins

Fixed inconsistent vendor names - (Task #474)

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java

Fixing closing of welcome screen.
---
Task #564: SWTBot: Fix welcome screen closing

Fixing closing welcome screen - (Task #564)

---

de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/FuncElectricalDiagramTest.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java

Adding SWTBot Graphiti Diagram test cases for testing different FuncElectrical
Diagram actions.
---
Task #568: Test Funcelectrical Graphiti Diagram

SWTBot: Added: FuncElectrical Diagram test cases - (Task #568)

---

de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java

Added milliseconds to units creation script - (Task #486)

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/command/CreateDeleteWithReferencingCategoryAssignmentsCommand.java
de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtilTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtil.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/DeleteCategoryAssignmentHandler.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/DeleteStructuralElementInstanceHandler.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/structure/dialog/ReferencedDeleteDialog.java

- This removes duplicate references
closes #660

Remvoing duplicate messages when removing referenced objects

---

de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java

Trying to delete referenced CA and SEI and checking that there is a warning popup.
closes #655

Added SwtBot test for deleting referenced objects - (Task #655)

---

de.dlr.sc.virsat.external.lib.jfreechart/META-INF/MANIFEST.MF

- Added license plugin as package export to manifest file
Closes #688
---
Task #688: Warning in jfreechart external lib plugin

Exporting license package in jfreechart external lib plugin

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepositoryTest.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepository.java

Now retrieve the ed if a project is already checked out in the ServerRepository
---
Closes Task #726: Missing Editing domain in REST Server

Added missing ed for existing projects to ServerRepository- (Task #726)

---

de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/VirSatNavigator.java

When dropping from the concept palette to navigator, the navigator expands to
target level.
closes #31 
---
Task #31: Expand navigator on drag and drop from concept palette

Expand navigator to target when drag & drop - (Task #31)

---

de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelperTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java

- Added units for Specific Heat Capacity and Thermal Conductivity
- Added new QKs Thermal Contact Resistance, Thermal Contact Conductance,
Thermal Contact Conductance per Unit Area and their associated units
Closes #729
---
Task #729: Units for Thermal Applications

Added new units and quantity kinds for thermal domain - (Task #729)

---

de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java

Missing default constructor using the default current local time was added.
Closes #735
---
Task #735: Excel Exporter/Importer Wizard creates "Excel IO Failed
Exception"

Added missing default constructor in ExcelExporter Classes - (Task #735)

---

de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/wizards/HTMLExportPage.java
de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/html/ExportHelper.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java

- Fixed a bug in the exporter when setting the destination via keyboard
- Implemented test case for exporting FEA elements to HTML
- Refactored some general purpose methods for opening VirSat exporters / importers
- Fixed bug with path separators on Linux systems
Closes #757

SWTBot Test case for FEA exports into HTML

---

de.dlr.sc.virsat.graphiti.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/VirsatDiagramFeatureProviderWithPatterns.java

Added VirSat diagram feature provider with patterns - (Task #763)

---

de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramUpdateBehavior.java

Added method to provide auto update functionality - (Task #766)

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java

Closes #745
---
Task #745: SWTBot Test Cases for DrillDown

Add SWTBot test cases for drill down - (Task #745)

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/wizard/AImportExportPage.java

- Created a SWTBot test for testing the wizard for exporting and importing .mat files
- Fixed bug in general import export page to support keyboard input
- Some general refactordings to impove code quality in the SWTBot test cases for exporters and importers
Closes #762

SWTBot Test for Exporting and Importing .mat files

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java

- Implemented test case for the CAD wizard, performing a CAD export and then a re-import
Closes #769

SWTBot Test for CAD Export/Import

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/PowerSummaryTest.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java

Created a power summary above two power equipments in a configuration tree. Compared the
expected values with test values.
Added PowerSummaryTest to AllTests
---
closes #746: SWTBot Test Cases for Power Summary

Added PowerSummaryTest - (Task #746)

---

de.dlr.sc.virsat.model.ext.core.edit.test/about.html
de.dlr.sc.virsat.model.ext.core.edit.test/build.properties
de.dlr.sc.virsat.model.ext.core.edit/about.html
de.dlr.sc.virsat.model.ext.core.edit/build.properties
de.dlr.sc.virsat.model.ext.core.test/about.html
de.dlr.sc.virsat.model.ext.core.test/build.properties
de.dlr.sc.virsat.model.ext.core/about.html
de.dlr.sc.virsat.model.ext.core/build.properties
de.dlr.sc.virsat.model.extension.funcelectrical/plugin.properties
de.dlr.sc.virsat.model.extension.tests.edit/plugin.properties
de.dlr.sc.virsat.model.extension.tests.ui/build.properties
de.dlr.sc.virsat.model.extension.tests/META-INF/MANIFEST.MF
de.dlr.sc.virsat.model.extension.tests/build.properties
de.dlr.sc.virsat.model.extension.tests/plugin.properties
de.dlr.sc.virsat.model.external.tests.edit/about.html
de.dlr.sc.virsat.model.external.tests.edit/build.properties
de.dlr.sc.virsat.model.external.tests/about.html
de.dlr.sc.virsat.model.external.tests/build.properties
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/LicenseTest.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java

Added a test that checks that licensing information is present in all features and plugins, and vendor is correctly set
Fixed issues revealed with this test
Closes #774

Feature/task 774 swt bot to check that 

---

de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/provider/RequirementsAttributeDefinitionTableLabelProvider.java

- Implement the label providers image selection of composed property
instances to forward it to the composed property
Close #697

Fix NPE in requirements attribute label provider - (Task #697)

---

de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetTableRequirementVerificationDefaultVerification.java

- Add new verification method only after its type selection dialog was
closed successfully
Closes #787

Refactor Initialization of Requirements Verification

---

de.dlr.sc.virsat.project.ui/plugin.xml
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/ChangeValueHandler.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/RenameHandler.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java

- Implemented ChangeValue handler for changing values of value property instances in the navigator and registered in plugin.xml
- Implemented Rename handler for renaming objects of type IName in the navigator and registered in plugin.xml
- Enabled both handlers to be invoked with F2
- Supported F2 to enable editing of cells in tables
Closes #775

Implemented Rename and ChangeValue handlers and F2 behavior

---

de.dlr.sc.virsat.graphiti.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/handler/AOpenInDiagramEdiorHandler.java
de.dlr.sc.virsat.model.extension.statemachines.ui/plugin.xml
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/propertyTester/OpenStateMachineTester.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/editor/StateMachineDiagramEditor.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/handler/OpenStateMachineInDiagramEditorHandler.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/StateMachineDiagramTest.java

- Supported opening & creating new state machine diagrams directly from the navigator
- Implemented generalized functionality for making handlers to open graphiti editors
Closes #234

Improved creation of state machine diagrams

---

de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDiagramFeatureProvider.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineAddFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateLayoutFeature.java

- Enabled default resize feature for states
- Implemented layout feature for states that positions all internal
objects (ellipse, intital state marker, etc) according to the state size
---
Task #810: Support resizing of States in StateMachines

Introduced state layout feature - (Task #810)

---

de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetSectionRequirement.java
de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/snippet/UiSnippetSectionVisualisation.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java

- Add a clear button to Resource, Reference & EReference property
snippet sections
Closing #823

Add a "Clear" button for properties 

---

.github/workflows/main.yml
.mailmap
bash/verify_commit_authors.sh
known_authors.txt

- Added kempra to known authors
- Added kemp_ra to mailmap mapping to kempra

Added kempra to known_authors and kemp_ra to mailmap

---

de.dlr.sc.virsat.model.extension.requirements/plugin.xml
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AAttributeValue.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ADefaultVerification.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AEnumerationDefinition.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AEnumerationLiteral.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AExistenceVerification.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AIVerification.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AModelVerification.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirement.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementAttribute.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementGroup.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementLink.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementObject.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementType.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsConfiguration.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsSpecification.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AVerificationConfiguration.java
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AVerificationType.java
de.dlr.sc.virsat.model.extension.tests/META-INF/MANIFEST.MF
de.dlr.sc.virsat.model.extension.tests/build.properties
de.dlr.sc.virsat.model.extension.tests/plugin.properties

Closes #864
---
Task #864: Regenerate generated concept classes

Commiting fully regnerated code - (Task #864)

---

de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc

Closes #854
Added a subsection with relevant properties for different shapes.

Expanded Visualisation Concept chapter in User Manual - (Task #854)

---

.mailmap
known_authors.txt

Add @maurpa to mailmap and known authors
Closing #874

Add Paulina to known authors

---

known_authors.txt

Closes #876
---
Task #876: Add George to known authors

Added George to known authors - (Task #876)

---

.mailmap

Put your Message here.
---
Task #876: Add George to known authors

Added George to mailmap

---

de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/auth/filter/CorsFilter.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepoHelper.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/RepoManagementServlet.java
de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java

Fixed following bugs:
- Registered CORS Filter on Management Servlet and added allow all headers in CORS Filter
- Moved repository registration step to the end of function to avoid invalid configurations
- Set credentials in git backend for private repositories
Closes #943

Fixed critical server bugs for release

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProvider.java

This fixes the NPE.
Also added a test case.
Closes #945: Fix nullpointer on PUT of Sei via server

Added missing adapter to TransactionalJsonProvider - (Task #945)

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
de.dlr.sc.virsat.server/doc-gen/model/paths.adoc
de.dlr.sc.virsat.server/doc-gen/model/swagger.json
de.dlr.sc.virsat.server/doc-gen/model/swagger.yaml
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java

Added delete endpoints to the REST API for CAs and SEIs.
Closes #949

Added delete endpoints to server

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposed.java
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling_Defaults.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling_NullComposition.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryComposition_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryIntrinsicArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling_NullReference.json
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposedTest.java

Add special handling for composed beans.
Update test resources.
Closes #1005
Closes #997 (duplicate)

Added is calculate method for bean properties

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/PropertyResourceTest.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/PropertyResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/StructuralElementInstanceResource.java

Also fix minor bug in Swagger Documentation of SEI and CA resources.
Closes #995

Added endpoint to download file resource to PropertyResource

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/wizard/ATreeViewerPage.java

Moved TreeViewer style for importers/exporters to a protected field
Closes #1015

Overriding of TreeViewer for exporters / importers - (Task #1015)

---

de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBooleanTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReferenceTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnumTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloatTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyIntTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResourceTest.java
de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyStringTest.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanValueProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReference.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnum.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResource.java
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling_Defaults.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling_NullComposition.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryComposition_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryIntrinsicArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling_NullReference.json
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReferenceTest.java

Added override field to property beans as this data is required for some external tools e.g. FreeCADmod
Closes #1017

Added override field to property beans

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnum.java
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling_Defaults.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling_NullComposition.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryComposition_Marshaling.json

Expose new unit bean for enum properties - (Task #1048)

---

.github/ISSUE_TEMPLATE/release.md

Added server API version numbers to release issue template

---

de.dlr.sc.virsat.test.feature/feature.xml

Added the missing registration in the feature.xml.

Added registration in virsat.test.feature for thermal.test plugin - Task #1069

---

de.dlr.sc.virsat.model.extension.budget.mass.test/src-gen/de/dlr/sc/virsat/model/extension/budget/mass/migrator/AMigrator1v4Test.java
de.dlr.sc.virsat.model.extension.budget.mass.test/src-gen/de/dlr/sc/virsat/model/extension/budget/mass/test/AllTestsGen.java
de.dlr.sc.virsat.model.extension.budget.mass.test/src/de/dlr/sc/virsat/model/extension/budget/mass/migrator/Migrator1v4Test.java
de.dlr.sc.virsat.model.extension.budget.mass.ui/plugin.xml
de.dlr.sc.virsat.model.extension.budget.mass/concept/concept.concept
de.dlr.sc.virsat.model.extension.budget.mass/concept/concept.xmi
de.dlr.sc.virsat.model.extension.budget.mass/concept/concept_v1_4.xmi
de.dlr.sc.virsat.model.extension.budget.mass/plugin.xml
de.dlr.sc.virsat.model.extension.budget.mass/src-gen/de/dlr/sc/virsat/model/extension/budget/mass/migrator/AMigrator1v4.java
de.dlr.sc.virsat.model.extension.budget.mass/src/de/dlr/sc/virsat/model/extension/budget/mass/migrator/Migrator1v4.java
de.dlr.sc.virsat.model.extension.requirements.test/src-gen/de/dlr/sc/virsat/model/extension/requirements/migrator/AMigrator0v7Test.java
de.dlr.sc.virsat.model.extension.requirements.test/src-gen/de/dlr/sc/virsat/model/extension/requirements/test/AllTestsGen.java
de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/migrator/Migrator0v7Test.java
de.dlr.sc.virsat.model.extension.requirements/concept/concept.concept
de.dlr.sc.virsat.model.extension.requirements/concept/concept.xmi
de.dlr.sc.virsat.model.extension.requirements/concept/concept_v0_7.xmi
de.dlr.sc.virsat.model.extension.requirements/plugin.xml
de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/migrator/AMigrator0v7.java
de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/migrator/Migrator0v7.java

- Use isVerification keyword to specify verification elements
- update version of math and requirements concept's version as their
concept was affected by this change
Closes #1058

Update requirements concept to new concept language

---

known_authors.txt

Removing Peter from Known Authors List for Offboarding

Peter_KnownAuthorsList_Removal

---

.mailmap
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/commonSorter/VirSatNavigatorSeiSorter.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatProjectContentProvider.java

Tested on KatSat, seems to be the same order (checked top level and some random nested components)
Closes #1088

Changed VirSatNavigatorSeiSorter to return zero - Task #1088

---

de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/scoping/ConceptLanguageScopeProvider.xtend
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/scoping/ConceptLanguageScopeProvider.java

Replaces the plugin loading based approach for checking for verificaitions with an EcoreUtil.resolve on the proxies.

Fix linking of requirement verifications in downstream projects - Task #1116

---

de.dlr.sc.virsat.product/virsat_core.product
de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
de.dlr.sc.virsat.target/virsat_windows.target
de.dlr.sc.virsat.team/META-INF/MANIFEST.MF

Changed update sites for svn connector and version upgrade - Task #1121

---

.mailmap
known_authors.txt

Add philipp and dennis to known authors file

---

README.md
de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
de.dlr.sc.virsat.target/virsat_linux.target
de.dlr.sc.virsat.target/virsat_windows.target

Fix repo locations to use https in target definitions

Update http links to https in tmodel

---

.mailmap
de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc

Task #1131 Fix phrasing and typos

---

.github/ISSUE_TEMPLATE/release.md

Any other things to update in the release checklist?

Update release.md to latest release process

---

de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramUpdateBehavior.java
de.dlr.sc.virsat.graphiti/META-INF/MANIFEST.MF
de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/util/DiagramHelper.java

- Improved decoding of urls
- improved logging
Closes #1132
Replaces #1206

Fioxing issue with decoding url in diagram editor

---

de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/EquationHelper.java

This change adds exception handling inside the equation builder.
If the evaluation of some equation fails, the builder will continue to evaluate (unrelated) equations instead of failing completely.

Improve robustness of equation builder
