de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatPasteFromClipboardCommand.java

- When pasting: Setting the discipline of nested child seis also to the discipline of the target object.
---
Task #26: Copying elements with nested elements of another disicpline
fails

Setting discipline of nested elements - (Task #26)

---

.travis.yml
de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/treemanager/networking/ZMQSocket.java

Closes #42 
---
Task #42: Don't crash the whole VirSat if visualisation ports are in use

Removed system exit on port binding exception - (Task #42)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java

Add null checks for using the table snippet outside of workbench-editor.
Closes #117

Add null-checks for editor site - (Task #117)

---

de.dlr.sc.virsat.product/virsat_core.product

- Added features using the "Add Required" button in product
configuration to get missing features
- Updated launch configuration to start felix.scr instead of equinox.ds
felix.scr replaces equinox.ds, see also
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543428
---
Task #269: Development build crashes immediately after selecting
workspace

Updated product Definition - (Task #269)

---

de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/markers/VirSatProblemMarkerHelper.java
de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetUtil.java

- Disabled notifications in resource isChanged
- Don't activate problem marker update in the editor if there was no
change to the resource diagnostic
---
Task #299: Editor update listeners are triggered multiple times on every
command

Don't send unnecessary notifications to editor listener - (Task #299)

---

de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java

Added a test case with the following setup:
- Multiple inheritance with no common ancestor
- The CA to be inherited has cardinality 1
Closes #140
---
Task #140: Check inheritance of cardinality one categories without
common ancestor.

Added test case for inheritance with no common ancestors - (Task #140)

---

de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitCommitAction.java

- Fixed IllegalArgumentException by checking if a path points to a
project.
Closes #347
---
Task #347: Commit directly after sharing a project in git fails

Fixed exception for first git commit - (Task #347)

---

de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelperTest.java
de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelper.java

- An earlier refactoring remove the necessary line to remember which set
function actually computes the value for the children.
- Added a comment for better clarity
- Added a regression test case
Closes #343
---
Task #343: Top Level Mass Summary Equation doesnt update

Fixed calculation bug introduced during an earlier refactoring - (Task #343)

---

de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitUpdateAction.java

- Peforming an update action with git now also triggers a refresh
---
Task #341: Updating with Git doesn't refresh Navigator

Added refresh after a git update action - (Task #341)

---

build.xml

- Explicitly excluding the "AllTests" test suite
- Only excluding classes that end with Test instead of having "Test"
somewhere in their name
Closes #367
---
Task #367: Improve code coverage report regarding classes with "Test" in
their name

Updated build.xml with more precise exclusion statements - (Task #367)

---

de.dlr.sc.virsat.team.ui/about.html

It seems there was an out-of-date about.html in the team.ui plugin.
Replaced with the new default about html.
---
Task #335: Update about.html in team.ui

Replaced about.html in team.ui plugin with default about.html - (Task #335)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uieingine/ui/palette/ConceptPaletteView.java

This change hides a concept group from the palette if the concept does not contain any types that can be instantiated.
Closes #400

Only show concept section in palette if there are non-abstract types in it - (Task #400)

---

de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/plugin/GenerateUiPluginXml.xtend
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/plugin/GenerateUiPluginXml.java

- Fix checking if a editor snippet extension definition is needed not by
empty-check on categories but by non-abstract categories -> abstract
categries do not have UI

Only create editor snippet extension if needed

---

de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyIntTest.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java

Closes #523
---
Task #523 If an IntProperty is not set, getValue() in a bean should
return null instead of exception

Return null if IntProperty is not set - (Task #523)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/swt/forms/VirSatMouseWheelScrollRedirectListener.java

- Fix a NPE if the scrollable form of which events are redirected does
not have a parent form that is scrollable
Closes #466

Fix NPE in ScrollRedirectListner if no scroallable parent exists

---

de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java

- Removed cleanRootTis method.  The correct cleaning of instances, whose super tis have been deleted, is handled in the cleanSuperTis method.
- Added a more integration like test case to verify that the cleanSuperTis method is indeed enough to handle cleanup of invalidated instances in the case of a diamond shaped inheritance case

Remove obsolete method in inheritance copier

---

de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/commonSorter/LabelColumnSorter.java
de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetQuantityKindManagement.java
de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetUnitManagement.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetEStructuralFeatureTable.java

Implemented new LabelColumnSorter that provides generic functionality to sort a table according to 
* a selected column by the user,
* a sort direction (ascending, descending),
* and the label of the objects.
Small refactoring in generic snippets to exract creation process of a table viewer to make it easier to override just that logic instead of the entire setup process of the table viewer
Have some funny picture:
By default the tables are sorted ascending by Unit Name and Quantitiy Kind Name.
Apparantly you cant customize the placement of the sorting indicator (the arrow thing), as that seems to be somehow determined by the operating system.
Closes #30

Sortable columns in QUDV Editor

---

de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelperTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java

- Throwing an exception when the method convertFromSourceToTarget is called for units that have mismatching QKs (previous behavior was silently saying ok and just passing back the original value)
- Added a test case to verify that the exception is correctly thrown.
- Removed some unnecessary whitespaces
Though, apparantly nobody is actually even calling this function...?!
Closes #89
---
Task #89: Unit conversion Qudv is returning undesired value

convertFromSourceToTarget now throws IllegalArgumentException for mismatching QKs

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccessTest.java

The issue seems to be that git is cleaning up some files while the apache code for deleting the directory is being executed. So he fails to delete the directory because he cant delete a file in it which has has already been deleted.
Replaced the forceDelete call by a quietDelete call. According to the API quietDelete should behave as forceDelete except that it doesnt throw any exceptions. I dont think there is a point for introducing some elaborate exception handling scheme in the tear down which should simply just delete a directory......
Closes #629 
---
Task #629: Server test case sometimes fails due to locked file

Replaced force delete with quiet delete - (Task #629)

---

de.dlr.sc.virsat.build.ui/src/de/dlr/sc/virsat/build/marker/ui/MarkerImageProvider.java
de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/core/DvlmNamingConventionValidator.java
de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/perspective/CorePerspective.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ValidatorTest.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/SwtBotHyperlink.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetIName.java

- Testing name validation of Seis and Cas
- Testing linking between problem markers and editors (if you double click on a marker, the correct editor is opened)
- Testing existance of correct warning and error icons in GenericEditor
- Testing correct tooltips
- Testing focused expansion on all sections with warnings/errors
- Created SwtBotHyperlink class because SwtBot only supports Links natively which are somehow different from Hyperlinks in SWT. The text link used to focus expand only sections with warnings/errors uses Hyperlinks.
The tests are structured into 4 cases:
- Testing of Sei name validation
- Testing of Ca name validation
- Testing of warnings in generic editor
- Testing of errors in generic editor
More combinations would be possible this should cover most cases without …

Added test cases for validation

---

de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java

Added some statements to close & reopen the editor and verify that the correct expansion state.
Closes #654
---
Task #654: Extend collapse section test case

Extended test case for collapsing sections - (Task #654)

---

de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelperTest.java
de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelper.java

Old approach: Removed entire category assignment and all contained
typeinstances from the inputs of set functions. This prevented the
creation of cycles. But also is responsible for the bug #635 since now
the PowerState category assignments in a PowerEquipment are disregarded
for the questions. Therefore, no update occurs.
New approach: Remove only the ca itself and the local property instances
from the inputs. Nestedely contained type instances are still considered
as potential inputs.
Also added a new test case modeling the situation of the power budget
concept.
Closes #635
---
Task #635: Equations for Power Concept do not update

Changed handling of nested categories in set functions - (Task #635)

---

de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/editor/snippet/UiSnippetEquations.java

- The Equation section edit button is no longer checked for rights
management
- The perform update button is now checked for rights management
Closes #374
---
Task #374: Add ability to see equations of not owned elements

Exchanged write access checks in snippet for equation section

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/list/ArrayUpdateTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/ReferenceUpdateTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryBase.java
de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryReference.java

The bug with re-referencing #486 is not reproducing with the new reference bean.
So this request just adds a couple of test cases to test this functionality.

Test cases for checking values after reference change in a bean

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetBetaWarning.java

Changed envrionment -> environment
---
closes #698: Environment misspelled in beta warning

Corrected misspelled word - (Task #698)

---

de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/cellEditor/aproperties/ReferencePropertyCellEditingSupport.java

- Setting initial value of cell editor for reference properties to the
same text as the cell label
Closes #86
---
Task #86: Reference property in table of containing SEI shows
toString()-Output when clicking into property table

Initializing value of cell editor for reference properties  - (Task #86)

---

de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/EquationHelperTest.java
de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/NumberLiteralSetterTest.java
de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/extensions/NumberLiteralSetter.java

- Checking if the target property is an int property. If so, the result
value is now cast to int before being set
Closes #700
---
Task #700: Calculation engine assigns double values to int properties

Added check for int type in setter - (Task #700)

---

de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/AExcelIo.java
de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExportHelper.java
de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/AExcelFuncIO.java
de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidator.java
de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/ImportValidator.java

Minor cleanup of the excel exporter constants.
- Removed excess FEA constants in SM plugin
- Moved FEA constants from general excel plugin to FEA plugin
- Improved readability of some general excel exporter constant names
Closes #737 
---
Task #737: Refactor column constants in excel exporters to appropriate
classes

Refactored excel exporter constants - (Task #737)

---

de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling.json
de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling_ChangeReference.json
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryAllPropertyTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryBeanATest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryCompositionArrayTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryCompositionTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryIntrinsicArrayTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryReferenceArrayTest.java
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryReferenceTest.java

- Added idempotency test cases
- Added test cases for reference and composed dynamic lists
- Discovered that to add an element in these lists, the wrapping rpi/cpi
has to exist in the model.
- Improved the reference test case to also change the referenced ca.
Closes https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/734

Added test cases for idempotency and dynamic lists for BeanCategoryAssignments unmarshalling

---

de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/elements/ElementLayoutFeature.java
de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/interfaceends/InterfaceEndAddFeature.java
de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/interfaceends/InterfaceEndMoveFeature.java
de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/utils/DiagramUtils.java

- Fixed switched up classification of left and right hand side interface
ends
- Added missing sorting call of interface ends
Closes #749
---
Task #749: InterfaceEnds in right side of element block in FEA diagrams
cannot have position changed

Fixed position correction int FEA diagrams of interface ends on right side of an element - (Task #749)

---

de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/VirSatChangeColorFeature.java
de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/InterfaceDiagramFeatureProvider.java

- Extended the VirSatChangeColorFeature to support changing the color of
connections
- Minor refactoring in the getCustomFeatures method of interface
diagrams to enable the generic features such as changing color and
opening editors as much as possible
Close #750
---
Task #750: Support color change of Interfaces / Connections

Extended functionality to support connection colors - (Task #750)

---

de.dlr.sc.virsat.swtbot.test/pom.xml

Closes #771
---
Task #771: Increase test timeout for SWTBot test cases

Increased test timeout value for SWTBot tests in pom - (Task #771)

---

de.dlr.sc.virsat.apps.test/resources/expectedGeneratorContent/AppManifest.MF
de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/ContentManifestMfTest.java
de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInititalizerTest.java
de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/initializer/ContentManifestMf.xtend
de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInitializer.java
de.dlr.sc.virsat.apps/xtend-gen/de/dlr/sc/virsat/apps/initializer/ContentManifestMf.java

- Made the target folder consistent to target/classes
- Added automatic module name to initial manifest
Closes #733
---
Task #733: App activation should produce project setup without warnings

Fixed app activation to stop producing warnings - (Task #733)

---

de.dlr.sc.virsat.graphiti.test/src/de/dlr/sc/virsat/graphiti/util/DiagramHelperTest.java
de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanDirectEditNameFeature.java
de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanPropertyFloatDirectEditValueFeature.java
de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/util/DiagramHelper.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDiagramFeatureProvider.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java

- Generalized update direct editing update feature to better work with
connection objects
- Fixed bad if check using some corrupted character
- Fixed diagram update not doing anything instead of updating all
elements in the diagram
Closes #337
---
Task #337: Name changes to transitions in state machine diagrams are not
updated in the model

Fixed direct editing update behavior - (Task #337)

---

de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanUnitValueProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanValueProperty.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBoolean.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposed.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReference.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnum.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResource.java
de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyString.java
de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/VirSatTransactionalAdapterFactoryContentProvider.java

- Renamed `ABeanProperty` to `ABeanValueProperty`
- Renamed `ABeanUnitProperty` to `ABeanUnitValueProperty`
- Added  `ABeanProperty` that wraps `APropertyInstance` and is extended by all bean property classes
- All bean constructores now use `super` instead of `setTypeInstance`
- Removed redundand `implements` statements
Closes https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/802

Fixed abstract BeanProperty classes inconsistency

---

de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/ExcelExporterTest.java
de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportWizard.java
de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExporter.java

- Added missing check that lead to always executing only the functional electrical architecture excel exporter
- Some minor code refactorings
Closes #336
---
Task #336: There seems to be no way to trigger the Excel Export of State
Machines

Added missing canExport check for calling exporters from the wizard

---

de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramBehavior.java

- Make sure the graphical viewer has an editor control when calculating
the real mouse location
- If no control exists yet because the editor is being initialized, then
simply return the native location to initialize the editor actions
Closing #816

Fix NPE when opening a graphiti diagram

---

de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java

Removed `Property Resource` that is not needed anymore because a abstract ABeanProperty for all bean properties was introduced in https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/802.
Closes https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/804

Removed PropertyResource

---

de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDoubleClickFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineAddFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateLayoutFeature.java

- Change color of states
- Fix states being resized incorrectly when defined as initial state
- Add rounding corners of state machine container shape
- Improve double click handling when clicked on transition labels
Closing #231

Improve look and feel of state machine diagrams

---

bash/maven_build.sh

- Grepping out irrelevant warnings
Closes #856 
---
Task #856: Improve build stability by excluding irrelevant warnings

Improved build stability

---

bash/setup.sh
de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/RoleManagementTest.java

- Re-added downloading and installing of Overtarget into Maven m2. Gost lost in a previous PR and only worked due to m2 caching.
- Changed to different version of DmfResourceTest (With a Class absed rule for timeout but without inheriting from AProjectTestCase which has a global timeout rule and causes jacoco issues on random)
- CHanged acquision of Problems view in RoleManagementTest to get it by ID rather than name since there are known issues from doing that in ValidatorTests.

Improved build stability 

---

.github/workflows/main.yml

- When a build failure occurs in the Build and Test Job, all reports generated by Surefire are uploaded
Closes #893
---
Task #893: Upload Surefire Reports in case of CI Failure

Uploading all surefire reports upon CI failure - (Task #893)

---

de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatProjectContentProvider.java

Forward content provider of composed property instance to its type instance to make the navigator cleaner...
Closing #901

Hide composed property instance 

---

de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelperTest.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelper.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AModelAccessResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/PropertyResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/StructuralElementInstanceResourceTest.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ApiErrorHelper.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/PropertyResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/StructuralElementInstanceResource.java

Added three create endpoints and test cases for:
- RootSei in ModelAccessResource
- Sei in StructuralElementInstanceResource
- Ca in CategoryAssignmentResource
Also added some minor improvement in the server errors.
@SaMuellerDLR the only think we don't handle at the moment are composed beans. For example what if one wants to create a ca inside a composed bean?
Closes #964

Added create endpoints

---

de.dlr.sc.virsat.test.feature/feature.xml

Registered the budget.cost model extension plugin in the test.feature so it gets deployed into the p2 repository.

Added budget.cost test plugins into test feature - Task #1091

---

de.dlr.sc.virsat.model.feature/feature.xml

- Deploy jakarta.activation plugin in model.feature since it deploys jersey but jersey requires jakarta.activation
- Otherwise the concept tools cannot be installed into an IDE due to the missing jakarta.acivatation plugin, since model.edit in return requires jersey

Deploy jakarta.activation - Task #1062

---

de.dlr.sc.virsat.external.lib.zmq.linux.x86_64/META-INF/MANIFEST.MF

Fixes the manifest file also for the zmq linux plugin.

Also removes native_lib from blundle classpath for zmq

---

de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetSectionExistenceVerification.java
de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java

Don't show property elementsToBeVerified as it is not relvant for the user (only for verification engine)
Closes #1107

Don't show toBeVerified UI in existenceVerification - Task #1107

---

.mailmap
de.dlr.sc.virsat.model.calculation.ui/META-INF/MANIFEST.MF
de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/editor/EquationSectionUriEditorInput.java
de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/editor/snippet/UiSnippetEquations.java
de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/serializer/EquationTransientValueService.java
de.dlr.sc.virsat.model.edit/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/provider/EquationSectionItemProvider.java
de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java
de.dlr.sc.virsat.model/model/dvlm.ecore
de.dlr.sc.virsat.model/model/dvlm.history
de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/CalculationPackage.java
de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/EquationSection.java
de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/impl/CalculationPackageImpl.java
de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/impl/EquationSectionImpl.java
de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/util/CalculationSwitch.java
de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java

Fix that equations were not opening if the containing CA was inherited.
-> superSei wasn*t defined as transiend, so XText couldn't handle its values
Fixed that equations have always been overwritten from the inheritance copier. The Inheritance copier actually always replaced every EMF containment.
-> Add overwrite flag to equation section
-> Changed copyContainment behavior of EMFCopier in our InheritanceCopier to not copy if there is an overwrite flag set.
-> Added UI to set and unset Overwrite-Flag in equation section
-> Automatically set overwrite flag if equations are edited

Bug fix: Equations do not open if element is inherited and equations cannot be overwritten

---

de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ConceptFragmentTestManifest.MF
de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ConceptPluginManifest.MF
de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ConceptPluginUiManifest.MF
de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/TestConceptValidator.java
de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/MANIFEST.MF
de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/ManifestMF.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/AFileContentGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFeatureBuildPropertiesGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFeatureXmlGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFragmentTestBuildPropertiesGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFragmentTestManifestGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginBuildPropertiesGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginExampleConceptGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginManifestGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginUiBuildPropertiesGeneratorTest.java
de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginUiManifestGeneratorTest.java
de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/ConceptLanguageGenerator.xtend
de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/validator/GenerateValidator.xtend
de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFragmentTestManifestGenerator.xtend
de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginManifestGenerator.xtend
de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginUiManifestGenerator.xtend
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/ConceptLanguageGenerator.java
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/validator/GenerateValidator.java
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptFragmentTestManifestGenerator.java
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginManifestGenerator.java
de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/project/filecontent/ConceptPluginUiManifestGenerator.java

Closes #879 
Closes #1130 
Updates the concept generator:
- Add server depenencies to new concept proejcts
- Update package location of SEIValidator
- Add java 11 automatic module header (we had a warning before)
- Changed way how the main-project name is derived from test & ui projects... before all 'ui' and 'test' strings were simply replaced... This was quite problemativ because it caused errors when the concept hat something with 'test' / 'ui' in its name
- Do a workspace refresh after generation is compelted to make sure icons are shown in the project explorer (also there we had a warning before that icons could not be found although they were generated)
No new concept project do not have warnings anymore. :)

Minor fixes to concept generators

---

de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/StateMachineDiagramToolBehaviorProvider.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/abstractConnection/AbstractConnectionAddFeature.java
de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/abstractConnection/AbstractConnectionCreateFeature.java

- when creating transitions using the state-machine diagram editor, a state can now be select both as source state and as target state of a transition, resulting in a self-loop
- automatically add bendpoints for newly created self-loops to improve usability

Enable creation of self-loops in state machines

---

de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Server_Manual.adoc
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServerTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AModelAccessResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/modelaccess/StructuralElementInstanceResourceTest.java
de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AJettyServerTest.java
de.dlr.sc.virsat.server/plugin.xml
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/Activator.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ApiErrorHelper.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResource.java
de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/StructuralElementInstanceResource.java

In this PR, we imrpove the generall usage and data access of our Virtual Satellite Headless Server.
Includes
- Enable customization of Port (and prints activated port)
- Return new objects instead of only their UUID on POST requests
- Improves error response if user does not have rights to modify data model (as specified in the Rolemanagement)

Improve data access via virtual satellite headless
